context:
  name: pispy-client
  version: "0.9.0"
  python_min: "3.10"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/p/pispy_client/pispy_client-${{ version }}.tar.gz
  sha256: dff96b598412c6d051a173550a532c39180da42b389376ac38e0a517584a1faa

build:
  noarch: python
  script: python -m pip install . -vv
  number: 0
  python:
    entry_points:
      pispy = pispy.__main__:run

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
  run:
    - python >=${{ python_min }}
    - httpx
    - packaging
    - textual >=0.68.0

tests:
  - python:
      imports:
      - pispy
      pip_check: true
      python_version: ${{ python_min }}.*
  - script:
    - pispy --help
    requirements:
      run:
        - python ${{ python_min }}.*

about:
  homepage: https://github.com/davep/pispy
  summary: 'A terminal-based Python package index inspector'
  description: |
    PISpy aims to be a simple but useful PyPI lookup client for the terminal.
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - claudiushaag
